services:
  api:
    image: fastapi-tdd/api:${VERSION}
    command: --reload
    tty: true
    stdin_open: true
    environment:
      - TESTING=${TESTING:-false}
      - DEBUG=${DEBUG:-false}
    ports:
      - 8000:8000
    volumes:
      - .:/code
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-root}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-root}
      - POSTGRES_DB=${POSTGRES_DB:-dev}
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:latest
    ports:
      - 6379:6379

volumes:
  pg-data:
