"""add account table

Revision ID: 1ae1d0bb6418
Revises: 
Create Date: 2025-02-21 14:25:09.358584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ae1d0bb6418'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ACCOUNT',
        sa.Column('id', sa.CHAR(36), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('password', sa.String(length=255), nullable=False),
        sa.Column('name', sa.String(length=30), nullable=True),
        sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ACCOUNT_email'), 'ACCOUNT', ['email'], unique=True)
    op.create_index(op.f('ix_ACCOUNT_id'), 'ACCOUNT', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ACCOUNT_id'), table_name='ACCOUNT')
    op.drop_index(op.f('ix_ACCOUNT_email'), table_name='ACCOUNT')
    op.drop_table('ACCOUNT')
    # ### end Alembic commands ###
