"""add is_verified field

Revision ID: 5b0451b2c170
Revises: 1ae1d0bb6418
Create Date: 2025-03-13 17:11:52.123253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b0451b2c170'
down_revision: Union[str, None] = '1ae1d0bb6418'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ACCOUNT', sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('ACCOUNT', sa.Column('verified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ACCOUNT', 'verified_at')
    op.drop_column('ACCOUNT', 'is_verified')
    # ### end Alembic commands ###
